name: flutter_spacer
description: "spacer is a Dart package for Flutter for easily spacing widgets in terms of percentage of screen width or height."
version: 1.0.3
repository: https://github.com/mstafamajid/Spacer

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

